# Form implementation generated from reading ui file 'about_wnd.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutForm(object):
    def setupUi(self, AboutForm):
        AboutForm.setObjectName("AboutForm")
        AboutForm.resize(627, 406)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QTextBrowser(parent=AboutForm)
        self.text.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.pushButton = QtWidgets.QPushButton(parent=AboutForm)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(AboutForm)
        self.pushButton.clicked.connect(AboutForm.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutForm)

    def retranslateUi(self, AboutForm):
        _translate = QtCore.QCoreApplication.translate
        AboutForm.setWindowTitle(_translate("AboutForm", "Что нового?.."))
        self.pushButton.setText(_translate("AboutForm", "Понятно.."))
