# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NMainWindow(object):
    def setupUi(self, NMainWindow):
        NMainWindow.setObjectName("NMainWindow")
        NMainWindow.resize(1129, 819)
        self.centralwidget = QtWidgets.QWidget(NMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        NMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_users = QtWidgets.QMenu(self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.menu_users.sizePolicy().hasHeightForWidth())
        self.menu_users.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 109, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.menu_users.setPalette(palette)
        self.menu_users.setObjectName("menu_users")
        NMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NMainWindow)
        self.statusbar.setObjectName("statusbar")
        NMainWindow.setStatusBar(self.statusbar)
        self.action_rasp = QtWidgets.QAction(NMainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_rasp.setFont(font)
        self.action_rasp.setAutoRepeat(False)
        self.action_rasp.setObjectName("action_rasp")
        self.action_journ = QtWidgets.QAction(NMainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_journ.setFont(font)
        self.action_journ.setAutoRepeat(False)
        self.action_journ.setObjectName("action_journ")
        self.action_exit = QtWidgets.QAction(NMainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_exit.setFont(font)
        self.action_exit.setObjectName("action_exit")
        self.menu_users.addSeparator()
        self.menu.addAction(self.action_rasp)
        self.menu.addAction(self.action_journ)
        self.menu.addAction(self.menu_users.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(NMainWindow)
        self.action_exit.triggered.connect(NMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(NMainWindow)

    def retranslateUi(self, NMainWindow):
        _translate = QtCore.QCoreApplication.translate
        NMainWindow.setWindowTitle(_translate("NMainWindow", "MainWindow"))
        self.menu.setTitle(_translate("NMainWindow", "Режим"))
        self.menu_users.setTitle(_translate("NMainWindow", "Сменить наставника ->"))
        self.action_rasp.setText(_translate("NMainWindow", "Расписание занятий"))
        self.action_rasp.setShortcut(_translate("NMainWindow", "Ctrl+1"))
        self.action_journ.setText(_translate("NMainWindow", "Журнал посещений"))
        self.action_journ.setShortcut(_translate("NMainWindow", "Ctrl+2"))
        self.action_exit.setText(_translate("NMainWindow", "Завершение работы"))
        self.action_exit.setShortcut(_translate("NMainWindow", "Ctrl+Q"))
