# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NMainWindow(object):
    def setupUi(self, NMainWindow):
        NMainWindow.setObjectName("NMainWindow")
        NMainWindow.resize(988, 700)
        self.centralwidget = QtWidgets.QWidget(NMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        NMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        NMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NMainWindow)
        self.statusbar.setObjectName("statusbar")
        NMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NMainWindow)
        QtCore.QMetaObject.connectSlotsByName(NMainWindow)

    def retranslateUi(self, NMainWindow):
        _translate = QtCore.QCoreApplication.translate
        NMainWindow.setWindowTitle(_translate("NMainWindow", "MainWindow"))
