# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TchWindow(object):
    def setupUi(self, TchWindow):
        TchWindow.setObjectName("TchWindow")
        TchWindow.resize(921, 684)
        font = QtGui.QFont()
        font.setPointSize(10)
        TchWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(TchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout.addWidget(self.tableView_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        TchWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TchWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        TchWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TchWindow)
        self.statusbar.setObjectName("statusbar")
        TchWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(TchWindow)
        QtCore.QMetaObject.connectSlotsByName(TchWindow)

    def retranslateUi(self, TchWindow):
        _translate = QtCore.QCoreApplication.translate
        TchWindow.setWindowTitle(_translate("TchWindow", "MainWindow"))
        self.menu.setTitle(_translate("TchWindow", "Журнал"))
